// apps/web/src/components/section-card.tsx
import type { ReactNode } from "react";

export function SectionCard(props: {
  title: string;
  description?: string;
  action?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="card">
      <div className="card-head">
        <div>
          <h2>{props.title}</h2>
          {props.description ? <p>{props.description}</p> : null}
        </div>
        {props.action}
      </div>
      <div>{props.children}</div>
    </section>
  );
}

// apps/web-vue/src/components/SectionCard.vue
<template>
  <section class="card">
    <div class="card-head">
      <div>
        <h2>{{ title }}</h2>
        <p v-if="description">{{ description }}</p>
      </div>
      <slot name="action" />
    </div>
    <div>
      <slot />
    </div>
  </section>
</template>

<script setup lang="ts">
defineProps<{
  title: string;
  description?: string;
}>();
</script>
